Fix/replace Error with beagle custom error
ZupIT/beagle-web-core pull request #268
Opened 2020-10-05 20:12 UTC by lbittencurt

**- What I did**
Addresses #236. I searched for the code, where there was the use of native Error and the cases I found I replaced with BeagleError. In my understanding none of them needed to create a new custom error to explain the context.

**- How I did it**
I have executed the changes oriented by the existing test cases.

**- How to verify it**
Run the unit tests.

**- Description for the changelog**
Replace native javascript generic Erros with Beagle custom error.

2020-10-05 20:19 UTC, Tiagoperes commented
Hey, thank you very much for the contribution! Please, don't mind the validation failure, this is a problem on our end in regards to external Pull Requests.

We are going to review your code asap ;)

2020-10-06 13:54 UTC, Tiagoperes requested changes
We still need to modify the errors in `src/service/view-content-manager/index.ts`

2020-10-06 13:54 UTC, Tiagoperes commented on src/action/send-request.ts
> +    if (!response.ok) throw new BeagleError(contextResponse.statusText)
Aqui seria melhor lançar um `BeagleNetworkError`:

```typescript
new BeagleNetworkError(url, response)
```

2020-10-07 12:47 UTC, Tiagoperes requested changes

2020-10-07 12:47 UTC, Tiagoperes commented on src/action/send-request.ts
> +    if (!response.ok) throw new BeagleNetworkError(url, contextResponse.statusText)
BeagleNetworkError receives two parameters:

1 - The url of the request.
2 - The response or a string. The intent is to provide the most information as possible. So, whenever you have the entire response object, use it. A string should only be used when the response object is not available.

As suggest in the previous review, you should use `new BeagleNetworkError(url, response)` instead of passing a string.

2020-10-08 13:33 UTC, Tiagoperes approved these changes

2020-10-08 14:46 UTC, hectorcustodiozup approved these changes

2020-10-09 12:42 UTC, Tiagoperes commented
I had to create an intermediary branch before sending the code to the master branch so the PR validation can be run. We really need to fix this problem with external pull requests.

2020-10-09 12:42 UTC, merged