Treats LocalView route types when PopToVIew
ZupIT/beagle-web-core pull request #269
Opened 2020-10-06 14:35 UTC by hectorcustodiozup

**- What I did**
Fixed problem where pop to view navigation would not work if the route passed was an identifier instead of URL
**- How I did it**
Checked the type of the route and verified any existing Identifiers that would match
**- How to verify it**
Run the branch and try to use navigation action pop to view
**- Description for the changelog**

Fixes popToView action with LocalView

2020-10-06 16:03 UTC, Tiagoperes requested changes
No core, é sempre necessário fazer testes quando se implementa uma feature ou um fix.

No caso do fix, se existia algo quebrado que não era detectado por um teste é pq tínhamos uma falha e um ou mais testes novos, que detectam essa falha, devem ser criados.

Sugestão:

- should pop to a local view
- should pop to first view matching the route: teste aquele caso em que eu falei que a sua regra não funcionaria, se tem url e screenIds iguais em diferentes rotas.

2020-10-06 16:23 UTC, Tiagoperes commented on src/beagle-view/navigator/index.ts
> +        const index = getRouteIndex(route, currentStack)
Use o `Array.findIndex`:

```typescript
function isRouteIdentifiedBy(route: Route, id: string) {
  return route.url === identifier || ('screen' in route && route.screen.identifier === screenId)
}

// ...

const index = currentStack.routes.findIndex(r => isRouteIdentifiedBy(r, route))
```

2020-10-07 18:06 UTC, Tiagoperes requested changes
Hector, lendo os novos testes, percebi um outro bug no popToView. Como está relacionado ao que vc fez, acho interessante já corrigir.

Além disso, na minha opinião, faltou um teste para verificar melhor que tudo funciona.

Explico melhor nos comentários quais os problemas e o que deve ser feito para corrigi-los.

2020-10-07 18:06 UTC, Tiagoperes commented on src/beagle-view/navigator/index.ts
> +        const index = currentStack.routes.findIndex(r => isRouteIdentifiedBy(r, route))
Para corrigir o problema que mencionei no arquivo de testes, é preciso fazer esse `findIndex` de trás pra frente, ou seja, primeiro olha o topo da pilha e por último a base dela.

Usando apenas javascript (sem libs):
```typescript
const reverseIndex = currentStack.routes.reverse().findIndex(r => isRouteIdentifiedBy(r, route))
const index = currentStack.routes.length - 1 - reverseIndex
```

Mas, acredito que a função do lodash seja bem mais clara, e nesse caso, aconselho importar essa função da lib:
```typescript
import findLastIndex from 'lodash/findLastIndex'
// ...
const index = findLastIndex(currentStack.routes, r => isRouteIdentifiedBy(r, route))
```

2020-10-08 13:37 UTC, Tiagoperes approved these changes

2020-10-09 18:05 UTC, carolinegoncalveszup approved these changes

2020-10-09 18:06 UTC, merged