Adds border styling support
ZupIT/beagle-web-core pull request #271
Opened 2020-10-07 17:41 UTC by hectorcustodiozup

**- What I did**
Added support to new style Border
**- How I did it**
Added the new property to the styling interface and created handler function
**- How to verify it**
Run branch and try using the new attribute border
**- Description for the changelog**

2020-10-07 18:35 UTC, Tiagoperes requested changes
Eu não cheguei a olhar o PR inteiro, pois notei um problema logo nos mocks criados. Foi mal se a task não tiver ficado clara na descrição da issue =(

Duas propriedades devem ser adicionadas: `borderWidth` e `borderColor`. Não existe `border`. `borderWidth` e `borderStyle` devem ser filhos direto do `style`.

Eu percebi também, pelo teste, que vc adiciona `borderStyle: solid`. É interessante fazer isso, se não a borda não aparece na maioria dos casos. Mas temos que tomar cuidado, suponha as seguintes situações:

1. O dev especificou `borderStyle` dentro do `style`, como esse estilo não é válido pro Beagle, ele vai ser usado como css, sem nenhum tipo de transformação. Isso funcionaria normalmente. Mas, a partir do momento em que vc seta `borderStyle` na mão, vc substitui o estilo que ele definiu no backend. A solução aqui é fácil, bastaria setar `borderStyle` pra `solid` apenas nos casos onde não existe `borderStyle` no objeto de estilo.

2. Imagine que o `borderStyle` esteja definido no front-end. Seu elemento vem do backend com `styleId: 'table-cell'` e vc tem no front uma classe css `table-cell` onde `borderStyle` é `dashed`. O estilo adicionado pelo Beagle é inline, ou seja, ele tem prioridade sobre a classe, dessa forma, vc vai adicionar, sem o dev saber um `borderStyle: solid`. O resultado é que o dev nunca vai conseguir usar o estilo que ele definiu no front-end, pois o Beagle fica inserindo `borderStyle` "magicamente". Uma solução seria obrigá-lo a trazer do backend, em `style`, o par `{ borderStyle: 'inherit' }`, mas isso não vai ser uma solução muito clara quando um dev se deparar com esse problema.

Por enquanto, acho que podemos deixar como vc fez. vamos apenas corrigir o primeiro cenário.

O segundo cenário é real e precisamos mantê-lo em mente, mas existe um workaround e acredito que o problema de setar `borderWidth` e `borderColor` e nenhuma borda aparecer é muito maior.

2020-10-08 14:00 UTC, Tiagoperes commented on __tests__/unit/old-structure/middlewares/beagleStyleMiddleware.spec.ts
> +  it('should handle border attribute', () => {
Sugestão: aqui vc combina dois testes em um só. É interessante separar comportamentos diferentes em testes diferentes. Isso facilita a identificação de bugs e impede que alguém remova o teste de um dos comportamentos por acidente.

Vc testa dois comportamentos aqui:
1. should convert border to css and include borderStyle
2. should convert border to css and not include borderStyle

No primeiro teste, vc deve avaliar o caso onde, além de converter borderWidth e borderColor, adiciona-se o borderStyle.

No segundo teste, vc deve avaliar o caso onde apenas se converte borderWidth e borderColor, sem incluir o borderStyle.

2020-10-08 14:09 UTC, Tiagoperes commented on src/beagle-view/render/styling.ts
> +  borderColor?: string,
Sobre os `| string`

- size: ok
- position: ok, pois pode vir o position do Beagle ou uma string css
- flex: ok, pois pode vir o flex do Beagle ou uma string css
- **cornerRadius: aqui o `| string` não faz sentido, pois `cornerRadius` não existe no CSS, essa é obrigatoriamente uma propriedade do Beagle.**
- **margin: aqui o `| string` fazia sentido, pois o dev pode especificar a margem como css, ao invés de usar o margin do Beagle.**
- **padding: aqui também fazia sentido o `| string`, pela mesma razão do margin.**
- **borderWidth: deveria ser um number, não uma string.**

2020-10-08 14:15 UTC, Tiagoperes requested changes

2020-10-08 14:15 UTC, Tiagoperes commented on src/beagle-view/render/styling.ts
> +  borderWidth?: string,
deveria ser um number, não uma string

2020-10-08 14:15 UTC, Tiagoperes commented on __tests__/unit/old-structure/middlewares/beagleStyleMiddleware.spec.ts
> +  it('should handle border attribute', () => {
Sugestão: aqui vc combina dois testes em um só. É interessante separar comportamentos diferentes em testes diferentes. Isso facilita a identificação de bugs e impede que alguém remova o teste de um dos comportamentos por acidente.

Vc testa dois comportamentos aqui:
1. should convert border to css and include borderStyle
2. should convert border to css and not include borderStyle

No primeiro teste, vc deve avaliar o caso onde, além de converter borderWidth e borderColor, adiciona-se o borderStyle.

No segundo teste, vc deve avaliar o caso onde apenas se converte borderWidth e borderColor, sem incluir o borderStyle.

2020-10-08 14:15 UTC, Tiagoperes commented on src/beagle-view/render/styling.ts
> +  borderColor?: string,
Sobre os `| string`

- size: ok
- position: ok, pois pode vir o position do Beagle ou uma string css
- flex: ok, pois pode vir o flex do Beagle ou uma string css
- **cornerRadius: aqui o `| string` não faz sentido, pois `cornerRadius` não existe no CSS, essa é obrigatoriamente uma propriedade do Beagle.**
- **margin: aqui o `| string` fazia sentido, pois o dev pode especificar a margem como css, ao invés de usar o margin do Beagle.**
- **padding: aqui também fazia sentido o `| string`, pela mesma razão do margin.**

2020-10-08 14:35 UTC, Tiagoperes approved these changes

2020-10-09 17:57 UTC, carolinegoncalveszup approved these changes

2020-10-09 17:57 UTC, merged