Feature/custom operations
ZupIT/beagle-web-core pull request #289
Opened 2020-10-20 14:23 UTC by hectorcustodiozup

**- What I did**
Added new option 'customOperations' to BeagleConfig interface
**- How I did it**
Created new property customOperation
Validated operations names and cast warnings when needed
Concatenated the default list of operations with the one given through the config

**- How to verify it**
Create custom operations and use them in expressions
**- Description for the changelog**
New option 'customOperations'

2020-10-23 17:20 UTC, Tiagoperes requested changes
I didn't check the tests yet. I'll only review the tests when the implementation is ok.

2020-10-23 17:20 UTC, Tiagoperes commented on src/service/beagle-service/types.ts
> +  /**
This is the documentation that appears to the user when he's programming. Please give more details:

Custom operations can be used to extend the capability of the Beagle expressions and are called like functions, e.g. `@{sum(1, 2)}`. Beagle has already many default operations, this configuration can be used to extend this initial set. The keys of this object represent the operation name and the values must be the functions themselves. An operation name must contain only letters, numbers and the character `_`, it also must contain at least one letter or `_`.

PS: You can write github markdown in these documentations, so, you can use the code delimiter (`) freely.

2020-10-23 17:20 UTC, Tiagoperes commented on src/beagle-view/render/expression.ts
> +  const fn = operationHandlers[operationName] as (...args: any) => any
use the type `Operation` here

2020-10-27 15:08 UTC, Tiagoperes requested changes

2020-10-27 15:08 UTC, Tiagoperes commented on src/service/beagle-service/configuration.ts
> +      throw new BeagleError(`Operation names must have only letters, numbers and the character _.
Infelizmente, quebras de linha e tabs aqui resultam em quebras de linhas e tabs na string final. Como não queremos replicar a formatação do nosso código na string de erro, não podemos colocar nem quebra de linha nem tabs aqui.

Por favor, coloque tudo na mesma linha.

2020-10-27 15:08 UTC, Tiagoperes commented on src/service/beagle-service/types.ts
> +   * Note: If you create custom operations using the same name of a default from Beagle, the default will be overwritten by the custom one
use ` para delimitar código. Por exemplo:
```
`@{sum(1, 2)}`
```

2020-10-28 19:23 UTC, hectorcustodiozup commented on src/service/beagle-service/configuration.ts
> +      throw new BeagleError(`Operation names must have only letters, numbers and the character _.
Nossa, não sabia disso. achei que o lint reclamaria pelo tamanho da linha.

2020-10-28 19:24 UTC, hectorcustodiozup commented on src/service/beagle-service/types.ts
> +   * Note: If you create custom operations using the same name of a default from Beagle, the default will be overwritten by the custom one
Coloquei só no que você sugeriu, não vi outra necessidade

2020-10-30 15:06 UTC, Tiagoperes approved these changes

2020-11-05 19:26 UTC, carolinegoncalveszup approved these changes

2020-11-05 19:48 UTC, merged