fix/alert
ZupIT/beagle-web-core pull request #292
Opened 2020-10-23 17:37 UTC by tayronemachadozup

**- What I did**
Fix the behavior of the alert when the message is an object.
**- How I did it**
Checking if message is a string or object.
**- How to verify it**
Checked through the unit tests.
**- Description for the changelog**
Closes #291

2020-10-23 20:04 UTC, Tiagoperes requested changes

2020-10-23 20:04 UTC, Tiagoperes commented on src/action/alert.ts
> +  if (typeof message != 'string') {
nunca use `!=` ou `==`, sempre use `!==` e `===`. Qual a diferença?

`'1' == 1` resulta em `true`
`'blah' == true` resulta em `true`

Mas, essas coisas tem tipos diferentes, deveria ser `false` o resultado.

Para fazer a operação de "estritamente igual", coloque um sinal de `=` a mais: `!==` e `===`.

2020-10-23 20:04 UTC, Tiagoperes commented on src/action/alert.ts
> +  const { onPressOk } = action
Não precisa fazer essa alteração, é melhor usar um ternário ao chamar `window.alert`.

2020-10-23 20:04 UTC, Tiagoperes commented on src/action/alert.ts
> +  }
ao invés de fazer esse if, mude a chamada abaixo para:

`window.alert(typeof message === 'string' ? message : JSON.stringify(message))`

2020-10-27 14:30 UTC, Tiagoperes requested changes

2020-10-27 14:30 UTC, Tiagoperes commented on src/action/types.ts
> +  message: string | Record<any, any>,
Não, não, vc entendeu errado, haha. O que eu quis dizer é que agora message pode ser qualquer coisa, portanto:

```typescript
message: any,
```

2020-10-27 14:41 UTC, tayronemachadozup commented on src/action/types.ts
> +  message: string | Record<any, any>,
Verdade Tiago. Vou fazer a alteração.

2020-10-28 17:27 UTC, Tiagoperes approved these changes

2020-11-05 19:11 UTC, carolinegoncalveszup approved these changes

2020-11-05 19:23 UTC, merged