Feature/deprecate screen identifier
ZupIT/beagle-web-core pull request #296
Opened 2020-10-26 12:49 UTC by hectorcustodiozup

**- What I did**
Deprecated screen identifier
**- How I did it**

**- How to verify it**

**- Description for the changelog**

2020-10-27 14:27 UTC, Tiagoperes requested changes

2020-10-27 14:27 UTC, Tiagoperes commented on src/beagle-view/navigator/types.ts
> +  id?: string,
Faça `Screen` estender `IdentifiableBeagleUIElement` ao invés de adicionar `id?: string`.

2020-10-27 14:27 UTC, Tiagoperes commented on src/beagle-view/navigator/types.ts
> +  /**
corrigir espaços

2020-10-27 14:27 UTC, Tiagoperes commented on src/beagle-view/navigator/types.ts
> + *  @deprecated since v1.4.0, please use id instead
O Beagle deu uma zoada nas versões. A próxima versão se chamará 1.5.0 e não 1.4.0.

2020-10-28 17:26 UTC, Tiagoperes requested changes

2020-10-28 17:26 UTC, Tiagoperes commented on src/beagle-view/navigator/types.ts
> +  * todo: remove screenComponent.identifier with the release of v2.0.0"
Coloque esse todo em um comentário separado com `// todo: ...`.

Não pode colocar junto pq os comentários no formato:

```typescript
/**
 *
 */
```

definem uma documentação. Ou seja quando vc coloca um "todo" dentro, vc está mandando esse texto pra dentro da documentação, e a gente não quer isso.

Essa documentação se chama `jsdocs` e ela parseada automaticamente pelo vscode quando alguém importa o Beagle. Ela é a informação que aparece quando um dev passa o mouse por cima de alguma função ou propriedade do Beagle.

2020-10-28 17:26 UTC, Tiagoperes commented on src/beagle-view/navigator/types.ts
> +import { BeagleUIElement, IdentifiableBeagleUIElement } from 'beagle-tree/types'
O `IdentifiableBeagleUIElement` não está mais sendo usado. Remover.

2020-10-28 18:09 UTC, carolinegoncalveszup approved these changes

2020-10-28 18:28 UTC, Tiagoperes approved these changes

2020-10-28 18:28 UTC, merged