Feature/history navigator
ZupIT/beagle-web-core pull request #298
Opened 2020-10-28 16:57 UTC by hectorcustodiozup

**- What I did**
Add new navigator BrowserNavigator
**- How I did it**
Created a new navigator using the window.history event handlers instead of a local navigation stack
**- How to verify it**

**- Description for the changelog**

2020-10-29 15:23 UTC, Tiagoperes requested changes
As promessas continuam não funcionando como o esperado. Eu acharia interessante vc resolver esse problema usando promessas, te ajudaria a dominar esse assunto.

De qualquer forma eu pensei em outra maneira que usa um estado adicional, mas não chega a ser um caso problemático de duas fontes de verdade. Vc pode ficar a vontade para implementar essa estratégia ao invés daquela que estávamos construindo antes.

Eu digo que, nesse caso, não chega a ser um problema as duas fontes de verdade, pois o novo estado não vai replicar 100% a estrutura do history e, assim que esse estado se dessincronizar com o browser, vamos lançar um erro, impedindo que as duas representações (estado local e history) fiquem diferentes.

Esse estado local seria um Array de Arrays, similar ao que temos no InternalNavigator, mas mais simples. Veja um exemplo:

`state = [['/home', '/sign-in'], ['/account', 'profile']]`

Cada Array é um stack com os identificadores das views. Para acessar a primeira view do primeiro stack, por exemplo, vc faria: `state[0][0]`.

Isso vai facilitar todas as operações de pop que desempilham mais de um estado, pois vc poderá fazer `history.go` ao invés de `history.back`. Veja um exemplo para o `popToView`:

```typescript
async function navigate(
    type: NavigationType,
    route?: Route | string,
    controllerId?: string,
  ) {
    const handlers: Record<NavigationType, () => Promise<void>> = {
      // ...
      popToView: async () => {
        if (!route || typeof route !== 'string') {
          throw new BeagleNavigationError(`Invalid route for popToView. Expected: string. Received: ${route}.`)
        }
       
        const currentStack = last(state)
        const index = lastIndexOf(currentStack, route)
        if (index === -1) throw new BeagleNavigationError('The route does not exist in the current stack')
        const amountOfViewsToPop = currentStack.length - index - 1
        currentStack.splice(index + 1, amountOfViewsToPop)
        history.go(-amountOfViewsToPop)
      },
     // ...
  }
  // ...
}
```

Ao cadastrar o listener do history ao window:

```typescript
function setupEventListener() {
    function popStateHandler(event: PopStateEvent) {
      if (!isEqual(event.state.route, last(last(state))) {
        // estourar uma exceção aqui e reiniciar o estado local garantem que o estado representado pelo histórico do browser será o mesmo que o representado pela variável local "state".
        state = []
        throw new BeagleNavigationError('Invalid browser history state! Beagle's navigation will stop working all together from now on. If you choose Beagle to control your browser state, make sure nothing else is also manipulating it. To deactivate Beagle's browser history interaction, please set "useBrowserHistory" to false when starting the BeagleView.`')
      }
      runListeners(event.state.route)
    }

    // popStateListener scope should be global to the browser navigator
    popStateListener = debounce(popStateHandler, 500)

    window.addEventListener('popstate', popStateListener)
  }
```

Dessa forma, criamos uma representação simples do estado que referencia o estado real que está no histórico do browser. Assim, podemos fazer `history.go()` diretamente para a posição que queremos. O fato de lançarmos exceções quando o estado local dessincroniza com o estado do browser e reiniciarmos o estado local, garante que os estados representam a mesma coisa.
---------

Outra coisa que precisamos melhorar é a repetição de código. Como reduzir a repetição entre o internal-navigator e o history-navigator?

---------
Atenção: eu comentei apenas na primeira vez que vi cada problema. Se o problema se repetiu no código, eu não comentei novamente.

2020-10-30 15:08 UTC, Tiagoperes commented
Closing this PR for now

2020-11-18 13:23 UTC, Tiagoperes requested changes

2020-11-18 13:23 UTC, Tiagoperes commented on src/beagle-view/navigator/browser-navigator.ts
> +        }
O código acima vai executar apenas um `back()`, ou seja, vc vai remover apenas a rota atual. Vc não queria um `while` ao invés de um `if`?

2020-11-18 13:23 UTC, Tiagoperes commented on src/beagle-view/navigator/browser-navigator.ts
> +          if (!history.state.isBeagleState)
Não seria um while ao invés de um if?

2020-11-18 13:23 UTC, Tiagoperes commented on src/beagle-view/navigator/browser-navigator.ts
> +          throw new BeagleNavigationError(`Invalid route for pushStack. Expected: Route object. Received: ${route}.`)
As strings de erro poderiam estar no arquivo de código compartilhado (todas).

2020-11-18 13:23 UTC, Tiagoperes commented on src/beagle-view/navigator/browser-navigator.ts
> +    return history.state.route
esse é o código para o `get` do `internalNavigator`:

```typescript
function get() {
  return cloneDeep(navigation)
}
```

Os navegadores devem implementar a mesma interface. Essa diferença me dis duas coisas:
1. A tipagem dessa interface deve estar errada.
2. Esse get deve ser reformulado para que faça sentido em ambos navegadores? Onde ele é usado? Realmente é uma função necessária?

2020-11-18 13:23 UTC, Tiagoperes commented on src/beagle-view/navigator/browser-navigator.ts
> +      if (isEqual(event.state.route, history && history.state)) return
Isso nunca vai ser verdadeiro. Vc não queria verificar `isEqual(event.state.route, history.state.route)`?

Quanto à verificação pelo history, ela não deveria existir aqui. Vc deveria verificar a existência do history ao iniciar o navegador e nunca mais. Se o history não existe, esse navegador não pode nem ser iniciado.

2020-11-19 13:11 UTC, hectorcustodiozup commented
Vou criar uma nova PR para a solução sem o uso de promises

2020-11-19 13:11 UTC, closed without merging