Feature/analitycs 2.0 queue configuration
ZupIT/beagle-web-core pull request #312
Opened 2020-12-16 14:12 UTC by tayronemachadozup

**- What I did**
Added queue for analytics 2.0 according to the epic ZupIT/beagle#745
**- How I did it**
Follow the definitions to implement the analytics queue.
**- How to verify it**
Using a poc in the beagle-creator it is in the branch react/poc-analytcs-2.0
**- Description for the changelog**
Added queue of analytics 2.0

2020-12-21 19:25 UTC, Tiagoperes requested changes
Todos os comentários são bem importantes e alguns precisam ser corrigidos. Portanto, não deixe de lê-los.

Sobre a solução em si, quando te expliquei como fazer, optei for fazer o menor número de mudanças possíveis ao código original, para que fosse algo fácil e rápido. Mas, infelizmente, apesar de ser possível arrumar os errinhos que eu comentei, o código está hiper-confuso. E nesse caso, apesar de economizarmos tempo agora, corremos risco de ter uma baita dor de cabeça em manutenções futuras. Por esse motivo, é melhor gastarmos um tempinho a mais e repensar a solução desse problema.

Esquecendo a implementação atual e pensando apenas no problema:
1. Não podemos gerar analytics record enquanto `provider.start()` e `provider.getConfig()` não tiverem terminado de executar. Mas, quando terminarem, o record deve ser gerado.
2. Devemos criar o record imediatamente se   `provider.start()` e `provider.getConfig()` já tiverem terminado.
3. Esse processo deve ser transparente para quem chama o AnalyticsService.

Vamos escrever isso em código:

```typescript
interface ActionRecordParams = {
  action: BeagleAction,
  eventName: string,
  component: IdentifiableBeagleUIElement,
  platform: string,
  route: Route,
}

createActionRecord(params: ActionRecordParams) {
  if(!hasStarted)  return addToQueue({ type: 'action', params })
  const { action, eventName, component, platform, route } = params
  // continue gerando a action
}
```

A ideia aqui é criar uma fila de chamadas. Ao chamar `createActionRecord` vamos verificar se é possível criar o record, se não for, vamos colocar na fila os parâmetros usados para chamar essa função e encerrar. Eu coloquei mais uma informação "type", pois precisaremos fazer o mesmo com `createScreenRecord`.

Sabemos se podemos ou não criar o record através da variável `hasStarted` que será `true` apenas quando `provider.start()` e `provider.getConfig()` tiverem terminado.

> Note que eu alterei o argumento da função `createActionRecord` para um objeto. Fiz isso, por muitos argumentos complicam a  chamada de uma fução, um objeto é mais simples. Será preciso alterar todos os lugares que usam essa função para fazerem a chamada correta.

Vamos alterar a função start para o seguinte:

```typescript
if (!provider) return
const startupResult = await Promise.all([provider.startSession(), provider.getConfig()])
config = startupResult[1]
hasStarted = true
createAnalyticsRecordsInQueue()
```

Aqui executamos a inicialização e esperamos `provider.start()` e `provider.getConfig()` terminarem. Assim que terminam, setamos `hasStarted` para `true`. A partir de agora, nada será incluido na fila, pois `hasStarted` será sempre true. Por último chamamos `createAnalyticsRecordsInQueue()` que vai re-executar todas as chamadas que foram previamente decartadas.

2021-01-18 17:15 UTC, theffc commented on src/service/analytics/index.ts
>      const shouldGenerateAnalytics = (isActionEnabled || (!isActionDisabled && isActionEnabledInConfig))
I might be wrong about how javascript works, but it seems to me that `!isActionDisabled` is equal to `isActionEnabled`, and so, the second part of the condition `(isActionEnabled || (!isActionDisabled && isActionEnabledInConfig))` would never be used

2021-01-22 19:57 UTC, Tiagoperes commented on src/service/analytics/index.ts
>      const shouldGenerateAnalytics = (isActionEnabled || (!isActionDisabled && isActionEnabledInConfig))
`isActionEnabled`: true only if the action was expressly enabled in the  json
`isActionDisabled`: true only if the action was expressly disabled in the  json

If the action didn't come with any analytics configuration, both `isActionEnabled` and `isActionDisabled` are false. Supposing your hypothesis is true, i.e, `!isActionDisabled == isActionEnabled`, we'd have `false == true`, which is impossible.

Hence, the hypothesis not correct and saying that `isActionDisabled` is false is not the same of saying `isActionEnabled` is true.

2021-01-22 20:41 UTC, Tiagoperes requested changes

2021-01-22 20:41 UTC, Tiagoperes commented on src/service/analytics/index.ts
> +    const shouldGenerateAnalytics = isActionEnabledInPayload && (isActionEnabledInPayload || isActionEnabledInConfig)
Be careful with these conditions, they were right before.

In first place, the condition in line 89 could be simplified. Here's what you have `A && (A || B)`. This is the same as saying `A`. Never write boolean expressions that can be further simplified.

After simplifying the condition you can clearly see that it's wrong.

Please, use the same conditions we used before (below). Attention: if the tests passes now, there's something wrong, they shouldn't.

```javascript
const isActionEnabledInPayload = !!action.analytics
const isActionDisabledInPayload = action.analytics === false
const isActionEnabledInConfig = config.actions[action._beagleAction_]
const shouldGenerateAnalytics = (isActionEnabledInPayload || (!isActionDisabledInPayload && isActionEnabledInConfig))
```

2021-01-22 21:13 UTC, tayronemachadozup commented on src/service/analytics/index.ts
> +    const shouldGenerateAnalytics = isActionEnabledInPayload && (isActionEnabledInPayload || isActionEnabledInConfig)
Simplifying the condition, I was able to verify there was really a problem.

2021-02-04 20:00 UTC, Tiagoperes requested changes

2021-02-04 20:00 UTC, Tiagoperes commented on src/service/analytics/types.ts
> +  getConfig: () => (AnalyticsConfig | null),
Essa docs não condiz mais com a realidade. Sugiro usar o um texto baseado na docs:

```javascript
  /**
   * Beagle uses this configuration to know how to handle analytics events. In order to access the
   * most updated global analytics config, this method is called whenever an event is triggered. It
   * can return an `AnalyticsConfig` or `null`. When `null`, the record is temporarily stored in a
   * queue. The enqueued records are processed when `getConfig()` returns a value different than
   * null.
   * 
   * @return an AnalyticsConfig or null
   */
```

2021-02-04 20:00 UTC, Tiagoperes commented on src/service/analytics/types.ts
> +  getMaximumItemsInQueue?: () => number,
Esse texto de documentação não é mais válido, sugiro copiar da docs:

```javascript
  /**
   * Represents how many records will be temporarily stored in a queue while `getConfig()` is `null`.
   * Defaults to `100`
   * 
   * @returns the maximum number of records in the queue
   */
```

2021-02-04 20:00 UTC, Tiagoperes commented on src/utils/promise.ts
> +/*
Acabou que não usamos isso, pode excluir.

2021-02-04 22:44 UTC, hectorcustodiozup commented on src/service/analytics/index.ts
> +  let createActionRecord: ((params: ActionRecordParams) => Promise<void>) // eslint-disable-line prefer-const
Como conversamos mantive habilitado pois por algum motivo o typescript não está entendendo a atribuição da variável. Deixei isso comentado

2021-02-04 22:47 UTC, hectorcustodiozup commented on src/service/analytics/index.ts
> +    queue.forEach(item => {
Muito bem lembrado, ficou bem mais enxuto o código. Fiquei em dúvida só se pensando em processamento o map tem vantagens sobre o foreach + Array.push ou se é só um atalho mesmo.

2021-02-10 18:57 UTC, Tiagoperes requested changes

2021-02-10 20:05 UTC, Tiagoperes commented
I consider this feature ready to go, the two commentaries above are easily solved. For this reason, this time I also analyzed the tests.

Here's a listing of the tests I expected to find. I marked with `(OK)` the ones I actually found. I also ignored every test related to the queueing system since we expect to remove this feature.

```
- (OK) Should create screen record when remote screen is loaded
- (OK) Should create screen record when local screen is loaded
- (OK) Should not create screen record when it is disabled in the config
- (OK) Should not create screen record when provider is unavailable

- (OK) Should create action record when action is fired
- (OK) Should not create action record when it is disabled in the config
- Should create action record when it is disabled in the config, but enabled in the action itself
- (OK) Should not create action record when it is enabled in the config, but disabled in the action itself
- (OK) Should create action record with exposed attributes according to the config
- (OK) Should resolve expressions when creating action record with expressions
- Should not resolve expressions in sub-actions when creating action record with expressions
- (ALMOST OK) Should create action record with exposed attributes according to the action itself, ignoring the attributes in the config
- (OK) Should create action record with additional entries
- Should interpret analytics object in action as if analytics is enabled.
- Should create action record with additional entries (action) and exposed attributes (config)
- Should create action record with additional entries (action) and exposed attributes (action)
- Should not create action record when provider is unavailable
```

The one I annotated with `(ALMOST OK)` is because we can't guarantee, through the test, that the attributes from the config are really being ignored. The title of the implemented test (`'should format the Action adding additional attributes from ACTION'`) also hints that the attributes are merged instead of replaced, which is not the case.

The test cases not marked with `(OK)` should be created.

2021-02-10 21:28 UTC, hectorcustodiozup commented
- Should interpret analytics object in action as if analytics is enabled.
 I did not understand what is expected from this test

- Should create action record with additional entries (action) and exposed attributes (config)
Isn't this case already covered here ?
![image](https://user-images.githubusercontent.com/50678762/107574277-4977fc80-6bcd-11eb-93a4-8ba1d71bb28a.png)

- Should create action record with additional entries (action) and exposed attributes (action)
Done

- Should not create action record when provider is unavailable
Done

2021-02-11 17:29 UTC, Tiagoperes approved these changes

2021-02-11 17:37 UTC, jamessonpenhazup approved these changes

2021-02-11 18:29 UTC, merged