Fix/analytics record interface
ZupIT/beagle-web-core pull request #321
Opened 2021-02-12 18:07 UTC by hectorcustodiozup

**- What I did**
Updated analytics interface
**- How I did it**
Created new interface specific for Action Records
**- How to verify it**
Through unit tests
**- Description for the changelog**

2021-02-12 18:24 UTC, tayronemachadozup approved these changes

2021-02-12 18:52 UTC, Tiagoperes requested changes

2021-02-12 18:52 UTC, Tiagoperes commented on src/service/analytics/actions.ts
> +    if ('screen' in currentRoute) record.screen = currentRoute.screen.identifier || currentRoute.screen.id
**suggestion (not needed for approval)**

It would be nicer to use the ternary operator here: `?`

```typescript
record.screen = 'screen' in currentRoute 
  ? currentRoute.screen.identifier || currentRoute.screen.id
  : currentRoute.url
```

2021-02-12 18:52 UTC, Tiagoperes commented on src/service/analytics/index.ts
> +    if (route && 'screen' in route) record.screen = route.screen.identifier || route.screen.id
**suggestion (not needed for approval)**

same

2021-02-12 18:52 UTC, Tiagoperes commented on src/service/analytics/types.ts
> +  component: Record<string, any>,
Avoid using `any` when you know what the type is:

```typescript
component: {
  type?: string,
  id?: string,
  position?: {
    x: number,
    y: number,
  },
  xPath?: string,
}
```

2021-02-12 19:12 UTC, hectorcustodiozup commented on src/service/analytics/actions.ts
> +    if ('screen' in currentRoute) record.screen = currentRoute.screen.identifier || currentRoute.screen.id
Changed it, much cleaner this way.

2021-02-17 17:57 UTC, Tiagoperes approved these changes

2021-02-17 19:00 UTC, tayronemachadozup approved these changes

2021-02-17 19:01 UTC, merged