Adds navigation state control
ZupIT/beagle-web-core pull request #326
Opened 2021-03-09 18:22 UTC by hectorcustodiozup

Closes #64
**- What I did**
Created array of navigated elements to restore then during pop navigation events
**- How I did it**
- Created array to keep track of visited routes
- Save elements on push events
- Restore elements on pop events

**- How to verify it**
- Creating an app, using the navigation events and checking if contexts values are kept
- Unit Tests

**- Description for the changelog**

Adds navigation state

2021-03-10 17:49 UTC, arthurbleilzup submitted a review, later dismissed

2021-03-11 20:47 UTC, Tiagoperes requested changes

2021-03-11 20:47 UTC, Tiagoperes commented on src/beagle-view/index.ts
> +      if (elementToRestore && elementToRestore._beagleComponent_ !== 'custom:error')
This might not work in some scenarios:

1. Suppose the design system of the app has a component called "custom:error" and it is explicitly specified by the bff. The action to navigate back would never work for pages with this component at the root element.
2. The error component is not hardcoded, it can be "custom:error" (default), but it can also be "custom:myError". You don't really know.

Do you really need to verify this? Considering the page has an error, how could someone possibly navigate forward? Considering it is impossible to navigate forward when the view has an error, we could never navigate back and find a view with an error. Or there's something I'm missing?

2021-03-11 20:47 UTC, Tiagoperes commented on src/beagle-view/index.ts
> +    navigator.subscribe(async (route, navigationController, elementToRestore) => {
Do we need a new parameter here? Can't we use route (the first parameter) instead?

The type of `route` can be either `LocalView` or `RemoteView`. Can't we use `LocalView.screen` to inform the view to restore? Just an idea, do you think it could work?

2021-03-11 20:47 UTC, Tiagoperes commented on src/beagle-view/navigator/index.ts
> +  let savedElements: Record<string, BeagleUIElement> = {}
This structure is probably not enough for your purpose. Consider the following sequence of steps:

1. Navigation starts at `Home`
2. User fills an input at the view `Home` with "Hello World"
3. User clicks the "Profile" in the menu and navigates to the view `Profile` (pushView)
4. At `Profile`, the user clicks "Home" in the Menu and navigates to the view `Home` (pushView)
5. The user clicks the button to go back, returning to "Profile"
6. The user clicks the button to go back, returning to "Home"
7. The input has no Text, "Hello World" has been erased.

This situation can happen because nothing prevents the user from creating a new instance of a view that already exists in the navigation stack and when it does so, the previous saved state is erased. This means the user can have a weird navigation stack like [X, Y, X, Z, W, Y, X]. The same is valid for a browser window, you can either go back to the previous page using the history or create a new instance of the page by typing the address directly.

This problem can be solved with two approaches:
1. We prevent Beagle from creating multiple instances of the same view. If the user is at X, pushes Y and then pushes X, the second X would not be a new version of X, instead, it would just navigate the user to the instance previously created.
2. We use another structure to save the state of a view. This structure must mimic the navigation stack. It can be either a new array or the navigation stack could be altered to also accept a state (BeagleUIElement).

The best thing to do here is to check with people responsible for Beagle Android and Beagle iOS. What do they do? We should implement a similar behavior.

2021-03-11 20:47 UTC, Tiagoperes commented on src/beagle-view/navigator/index.ts
> +        if (treeElement['onInit'])
As we discussed before, this is not a good solution. You should add a `fixme` here explaining why this is needed and why it still doesn't cover every case. Since it will still need some work, a new issue explaining the problem should be opened.

2021-03-11 20:47 UTC, Tiagoperes commented on src/beagle-view/navigator/index.ts
> +        savedElements = {
Theres's no need to replace the entire object. Let's save some memory.

1. Declare savedElements as a constant
2. Change only what you need: `savedElements[key] = treeElement`

2021-03-12 20:27 UTC, hectorcustodiozup commented on src/beagle-view/navigator/index.ts
> +        if (treeElement['onInit'])
Added the fixme. The issue still needs to be opened

2021-03-12 20:29 UTC, hectorcustodiozup commented on src/beagle-view/index.ts
> +      navigator = BeagleNavigator.create(navigationControllers, initialNavigationHistory, getTree)
The master version is also initializing this navigator twice, I gave it a quick look but could not find out why. It needs further attention but as it is not something I added in this pull request I am resolving this conversation.

2021-03-12 20:35 UTC, hectorcustodiozup commented on src/beagle-view/navigator/index.ts
> +  let savedElements: Record<string, BeagleUIElement> = {}
I changed my solution according to the tips you gave. Now, the route object accepts a new property ``state`` which is used to restore the element to its previous value when views are popped

2021-03-15 12:46 UTC, Tiagoperes commented on src/beagle-view/index.ts
> +      navigator = BeagleNavigator.create(navigationControllers, initialNavigationHistory, getTree)
I checked the code at master. This re-initializarion is actually necessary. It covers a legacy scenario and will be removed with v2.0.

2021-03-15 14:59 UTC, Tiagoperes requested changes

2021-03-15 14:59 UTC, Tiagoperes commented on src/beagle-view/navigator/index.ts
> +  }
lines 119-128 could be simplified to:

```typescript
last(getCurrentStack().routes).state = removeInitializers(stateTree)
```

where `removeInitializers` is a function that removes events like `onInit`.  We should probably think of a  better solution to do this, since initialization events won't necessarily be named `onInit`.

2021-03-15 14:59 UTC, Tiagoperes commented on src/beagle-view/navigator/types.ts
> +  elementToRestore?: BeagleUIElement
this is not needed anymore

2021-03-15 14:59 UTC, Tiagoperes commented on src/beagle-view/navigator/types.ts
> +export interface StateView {
how do we make a popToView in this scenario?

2021-03-15 14:59 UTC, Tiagoperes commented on src/beagle-view/navigator/types.ts
> +export type Route = LocalView | RemoteView | StateView
By changing this type we're also allowing a navigation to a state. This is not what we want.

2021-04-06 19:50 UTC, Tiagoperes commented
I have made all changes I considered necessary.

Overall, as previously discussed with Hector, I don't like this solution, it couples the BeagleView and BeagleNavigator way too much. Furthermore, having to tell what is an initialization event and what is not just to be able to properly save the state is really bad.

I think, maybe, we should look up to the solution used in the mobile frameworks here. Maybe the navigation should not be core to Beagle, instead, it should be part of Beagle React, Beagle Angular, etc. This way, we could use the framework tools to properly store the rendered React tree or Angular tree.

2021-04-06 20:11 UTC, jamessonpenhazup approved these changes

2021-04-06 20:18 UTC, arthurbleilzup approved these changes

2021-04-06 20:56 UTC, Tiagoperes approved these changes

2021-04-06 20:56 UTC, merged