Updates interface
ZupIT/beagle-web-core pull request #327
Opened 2021-03-10 17:15 UTC by hectorcustodiozup

**- What I did**
Updated Route interface according to this issue https://github.com/ZupIT/beagle/issues/1398
**- How I did it**
Added the new HttpData property to the Route interface and used it when fetching the view
**- How to verify it**
Passing the new property to the route structure in the payload
**- Description for the changelog**

2021-03-10 17:50 UTC, arthurbleilzup submitted a review, later dismissed

2021-03-11 15:09 UTC, Tiagoperes requested changes
There are somethings missing for this issue to be resolved.

## Beagle Core
### Beagle View
In `beagle-view/index.ts`, you need to change the signature of the function `createBeagleView`. But you can't just change it, it would be a breaking change. Instead you must deprecate it.

In other languages, this would be pretty simple:

```kotlin
@Deprecated(message = "...")
fun createBeagleView(service: BeagleService, networkOptions: NetworkOptions, initialControllerId: String): BeagleView {
  // ...
}

fun createBeagleView(service: BeagleService, initialControllerId: String): BeagleView {
  createBeagleView(service, null, initialControllerId)
}
```

In other languages, function signatures is what define a function, so `x(a, b, c)` is different than `x(a, b)`. In javascript, a function is defined solely by its name, hence, we can't overload a function and deprecate only one of the signatures.

Overloads in javascript are a bit different. What we need to do is to accept the following calls for `createBeagleView`:

1. `createBeagleView(service)`
2. `createBeagleView(service, networkOptions)` **_deprecated_**
3. `createBeagleView(service, networkOptions, controllerId)` **_deprecated_**
4. `createBeagleView(service, controllerId)`

So, our function, must be implemented like this:

```typescript
function createBeagleView(
  beagleService: BeagleService,
  networkOptionsOrInitialControllerId?: NetworkOptions | string,
  initialControllerId?: string,
): BeagleView {
  // todo: remove legacy code for v2.0
  let networkOptions: NetworkOptions | undefined
  if (typeof networkOptionsOrInitialControllerId === 'string') {
    initialControllerId = networkOptionsOrInitialControllerId
  } else {
    networkOptions = networkOptionsOrInitialControllerId
  }
  // end of legacy code
```

In my opinion, this is one of the worst things about javascript. There should be a better way to do overloads. If we received an object `options` instead of these tree parameters this change would be much, much simpler. But for cases like this, where the parameters are not an object, we must do overloads like this.

This works, now I can make all the calls listed above without a problem. But still, there is no deprecation. How to deprecate stuff in this scenario? Fortunatelly we use Typescript and Typescript does alow function overloads in its type definitions. Here's what we must do:

in `beagle-view/types.ts`:

```typescript
  /**
   * @deprecated since v1.7. Will be deleted in v2.0. Instead, please use `route.httpAdditionalData`
   * when making a navigation.
   */
  (
    beagleService: BeagleService,
    networkOptions?: NetworkOptions,
    initialControllerId?: string,
  ): BeagleView,
  (
    beagleService: BeagleService,
    initialControllerId?: string,
  ): BeagleView,
}
```

Now, you just need to use this as the type of the function `createBeagleView` in `beagle-view/index.ts`

```
const createBeagleView: CreateBeagleView = (
  beagleService: BeagleService,
  networkOptionsOrInitialControllerId?: NetworkOptions | string,
  initialControllerId?: string,
): BeagleView => {
  // todo: remove legacy code for v2.0
  let networkOptions: NetworkOptions | undefined
  if (typeof networkOptionsOrInitialControllerId === 'string') {
    initialControllerId = networkOptionsOrInitialControllerId
  } else {
    networkOptions = networkOptionsOrInitialControllerId
  }
  // end of legacy code
```

### Beagle Service

A simmilar function is also exported by the BeagleService, so a simmilar approach must be done there as well.

Please alter the property `createView` of the BeagleService declared in `service/beagle-service/index.ts` by deprecating the old signature of the function.

## Beagle Angular and Beagle React
The changes requested here are actually new PRs in beagle-angular and beagle-react.

This modification is so that the user can make the first request using anything he/she wants, without it interferring with the subsequent requests. So, the component `BeagleRemoteView` should be altered to accept the new kind of `route`.

Since the user will most of the time use a Get request with no headers, I think we should still let him/she use a string when specifying `route`. But, now we should also allow the usage of a full object. So the type of `route` in the parameters of a `BeagleRemoteView` becomes `string | RemoteView`.

Remember to treat this new type of `route` correctly when making the first navigation.

The parameter `networkOptions` of the component `BeagleRemoteView` should be deprecated.

2021-03-11 16:54 UTC, arthurbleilzup approved these changes

2021-03-11 19:15 UTC, Tiagoperes requested changes

2021-03-11 19:15 UTC, Tiagoperes commented on src/beagle-view/index.ts
> +   // todo: remove legacy code for v2.0
You need place this before making the initializations above.

This code fixes the parameters values, for this reason it MUST be the first thing the function does.

2021-03-11 19:27 UTC, Tiagoperes approved these changes

2021-03-11 20:13 UTC, arthurbleilzup approved these changes

2021-03-15 12:39 UTC, merged