Feature/updates contract for navigation
ZupIT/beagle-web-core pull request #332
Opened 2021-04-13 19:51 UTC by jamessonpenhazup

**- What I did**
Updated Route interface according to this issue ZupIT/beagle#1398
**- How I did it**
Added the type any in body of HttpAdditionalData
**- How to verify it**
Passing the new property to the route structure in the payload

**- Description for the changelog**

2021-04-14 12:39 UTC, arthurbleilzup submitted a review, later dismissed

2021-04-14 12:40 UTC, tayronemachadozup submitted a review, later dismissed

2021-04-14 19:40 UTC, Tiagoperes requested changes

2021-04-14 19:40 UTC, Tiagoperes commented on src/beagle-view/index.ts
> +        if (httpAdditionalData?.body && typeof httpAdditionalData.body !== 'string'){
this functionality has much to do with how the request is made to the backend and little to do with the beagle-view itself. For this reason, it would be better to place it inside the function `beagleService.viewClient.load` and not here.

2021-04-14 19:40 UTC, Tiagoperes commented on src/service/network/default-headers/types.ts
> +  get: (url: string, method: HttpMethod, body?: any) => Promise<BeagleDefaultHeaders | {}>,
why did you need to edit this type?

2021-04-14 19:40 UTC, Tiagoperes commented on src/service/network/view-client/index.ts
> +    const defaultHeaders = await defaultHeadersService.get(url, method, body)
why do you pass body? Does `defaultHeadersService.get` make use of this?

2021-04-20 15:16 UTC, Tiagoperes approved these changes

2021-04-20 16:43 UTC, arthurbleilzup approved these changes

2021-04-20 16:43 UTC, merged