Fixes + deprecations + descriptions
ZupIT/beagle-web-core pull request #341
Opened 2021-06-30 20:54 UTC by arthurbleilzup

**- What I did**
Implemented the `doTemplateRender` method on the Renderer API, following the suggestions described on the issue #338 

Closes: #338 and [ZupIT/beagle#1523](https://github.com/ZupIT/beagle/issues/1523)

2021-07-01 13:40 UTC, Tiagoperes requested changes

2021-07-01 13:40 UTC, Tiagoperes commented on src/beagle-view/render/expression.ts
> +const IGNORE_COMPONENT_KEYS = ['id', 'context', 'children', '_beagleComponent_', 'templates']
## Problem
id, context, children and \_beagleComponent\_ are all Beagle reserved words. By adding "templates" to this list, we make it so "templates" also becomes a reserved word. Do we want this?

This introduces a breaking change. If someone uses a component with a property named "templates", this component can stop working as soon as Beagle is updated.

I believe you did this because you needed the expressions to be intact when inside the rendering method of a ListView. This was not a problem before because, expressions are not processed for components inside a property, unless this property is called "children". But with this last change, we also need to prevent "case" from being interpreted and not just the template itself (view).

The first way we can achieve this is what you did, but it has a collateral effect to every component in Beagle, effectively creating a reserved word and making a breaking change.

## Alternatives
### Use a lifecycle on the ListView
The second way is by altering the ListView before it gets processed. You can tell Beagle that everytime a ListView is received it should make slight alterations to it. If you transform every template possibility into a component, then you won't have this problem anymore, because beagle ignores components inside properties that are not called "children". Example:

```json
{
  "_beagleComponent_":"beagle:listview",
  "templates":[
    {
      "case":"@{eq(item.type, 'person')}",
      "view":{
        "_beagleComponent_":"beagle:container",
        "style":{
          "display":"@{condition(eq(item.type, 'person'), 'FLEX', 'NONE')}"
        },
        "children":[
          {
            "_beagleComponent_":"beagle:text",
            "text":"PERSON:",
            "textColor":"#FF0000"
          },
          {
            "_beagleComponent_":"beagle:text",
            "text":"@{item.name} is @{item.age} years old."
          }
        ]
      }
    }
  ]
}
```

would become:

```json
{
  "_beagleComponent_":"beagle:listview",
  "templates":[
    {
      "_beagleComponent_":"beagle:listViewTemplate",
      "case":"@{eq(item.type, 'person')}",
      "view":{
        "_beagleComponent_":"beagle:container",
        "style":{
          "display":"@{condition(eq(item.type, 'person'), 'FLEX', 'NONE')}"
        },
        "children":[
          {
            "_beagleComponent_":"beagle:text",
            "text":"PERSON:",
            "textColor":"#FF0000"
          },
          {
            "_beagleComponent_":"beagle:text",
            "text":"@{item.name} is @{item.age} years old."
          }
        ]
      }
    }
  ]
}
```

Note:  the only change was the line `"_beagleComponent_": "beagle:listViewTemplate"`

### Use the Renderer API to get the original component
I think an even simpler solution would be to completely ignore the property "templates" received by the component and get it from the original tree, stored in the BeagleView.

Example in React:

```typescript
const templates: BeagleListViewInterface['templates'] = useMemo(() => viewContentManager.getElement().templates)
```

The `useMemo` is important because we need to avoid traversing the tree unnecessarily.

2021-07-01 13:40 UTC, Tiagoperes commented on src/beagle-view/render/index.ts
> +    mode: TreeUpdateMode = 'replaceComponent'
Please, don't change the current code formatting. Eslint should be validating this, but we always use trailing commas, don't remove it.

2021-07-01 13:40 UTC, Tiagoperes commented on src/beagle-view/render/types.ts
> +  doFullRender: (
Don't alter code formatting unnecessarily. Are you using a plugin that auto-formats files when saved? If yes, please disable it.

2021-07-01 13:59 UTC, arthurbleilzup commented on .editorconfig
> +end_of_line = lf
As discussed on Teams, `lf` is the right option, so I will resolve this change request

2021-07-01 15:30 UTC, arthurbleilzup commented on src/beagle-view/render/expression.ts
> +const IGNORE_COMPONENT_KEYS = ['id', 'context', 'children', '_beagleComponent_', 'templates']
As we discussed on a call and with your suggestions, I removed the `templates` prop from the reserved words of Beagle, and to solve the issue that we generate on `beagle:listview` and `beagle:gridview`, I will be using the third solution, and they will be available on the PRs of each platform (Angular and React).

2021-07-01 15:31 UTC, arthurbleilzup commented on src/beagle-view/render/index.ts
> +    mode: TreeUpdateMode = 'replaceComponent'
I think this is not a mistake made by an auto-plugin, maybe it was removed by myself unintentionally, but it is fixed right now.

2021-07-01 15:33 UTC, arthurbleilzup commented on src/beagle-view/render/types.ts
> +  doFullRender: (
I think this is not a mistake made by an auto-plugin and I do not remember a time where the method was declared in a single line, we will keep it with broken parameters following the other methods that we have on this object. Also I fixed the trailing comma.

2021-07-01 19:52 UTC, Tiagoperes requested changes

2021-07-01 19:52 UTC, Tiagoperes commented on src/beagle-view/render/types.ts
> +   doTemplateRender: (
There are some incoherences between the method definition and its parameters. Here's my suggestion:

```typescript
/**
 * Renders according to a template manager and a matrix of contexts.
 * 
 * Each line in the matrix of contexts represents an iteration and each column represents the value
 * of a template variable. For instance, imagine a template with the variables `@{name}`, `@{sex}`
 * and `@{address}`. Now suppose we want to render three different entries with this template.
 * Here's a context matrix that could be used for this example:
 * 
 * [
 *   [{ id: 'name', value: 'John' }, { id: 'sex', value: 'M' }, { id: 'address', value: { street: '42 Avenue', number: '256' } }],
 *   [{ id: 'name', value: 'Sue' }, { id: 'sex', value: 'F' }, { id: 'address', value: { street: 'St Monica St', number: '85' } }],
 *   [{ id: 'name', value: 'Paul' }, { id: 'sex', value: 'M' }, { id: 'address', value: { street: 'Bv Kennedy', number: '877' } }],
 * ]
 * 
 * Note that the parameter `contexts` adds to the context hierarchy that is already present in the
 * tree, it doesn't replace it, i.e. you can still use the contexts declared in the current tree.
 * 
 * For each line of the context matrix, a template is chosen from the template manager according to
 * `case`, which is a boolean or a beagle expression that resolves to a boolean. When `case` is an
 * expression, it's resolved using the entire context of the current tree plus the contexts passed
 * in the parameter `contexts` corresponding to the current iteration. If no template attends the
 * condition the default template is used. If there's no default template, the iteration is skipped.
 * 
 * After processing all items, the resulting tree is attached to the current tree at the node with
 * id `anchor` (passed as parameter).
 * 
 * The component manager is an optional parameter and is used to modify the resulting component.
 * This can be very useful for managing ids, for instance. The component manager is a function that
 * receives the component generated and the index of the current iteration, returning the modified
 * component.
 *
 * @param templateManager templates used to render each line of the context matrix.
 * @param anchor the id of the node in the current tree to attach the new nodes to.
 * @param contexts matrix of contexts where each line represents an item to be rendered according to
 * the templateManager.
 * @param componentManager optional. When set, the component goes through this function before being
 * finally rendered.
 */
```

2021-07-01 20:02 UTC, igorgiumellizup commented on src/beagle-view/render/types.ts
> +   * an expression, it's resolved using the entire context of the current tree plus the contexts
```suggestion
   * an expression, it's resolved using the entire context of the current tree, plus the contexts
```

2021-07-01 20:02 UTC, igorgiumellizup commented on src/beagle-view/render/types.ts
> +   * to `case`, which is a boolean or a beagle expression that resolves to a boolean. When `case` is
```suggestion
   * to `case`, which is a boolean or a Beagle expression that resolves to a boolean value. When `case` is
```

2021-07-01 20:02 UTC, igorgiumellizup commented on src/beagle-view/render/types.ts
> +   * will be used, but only if set, if it is not set the item will be not rendered.
```suggestion
   * will be used, but only if set. If not set, the item will be not rendered.
```

2021-07-01 20:40 UTC, Tiagoperes requested changes

2021-07-01 20:40 UTC, Tiagoperes commented on src/beagle-view/render/template-manager/index.ts
> +    item.case && Expression.resolve(item.case, contextHierarchy, operationHandlers) || !item.case
```suggestion
    item.case && Expression.resolve(item.case, contextHierarchy, operationHandlers)
```

2021-07-01 20:40 UTC, Tiagoperes commented on src/beagle-view/render/index.ts
> +      throw new BeagleParseError('The template to render was not provided!')
We avoid throwing errors while rendering, so if we fail to render a single component, we don't risk breaking the entire application.

Today, we throw an error only if the json structure expected by Beagle is mal-formed.

My suggestion would be to replace this with an error log and return.

```suggestion
     return logger.error(`Beagle can't do the template rendering at the node ${anchor} because it couldn't find any template to use. Please provide at least one template to the templateManager parameter.`)
```

2021-07-01 20:40 UTC, Tiagoperes commented on src/beagle-view/render/index.ts
> +    if (!anchor) throw new BeagleParseError('The anchor id to render a template was not provided!')
same.
```suggestion
    if (!anchor) return logger.error('Beagle can\'t do the template rendering because no anchor has been provided. Beagle needs to know where to place the new nodes within the current tree.')
```

2021-07-01 20:40 UTC, Tiagoperes commented on src/beagle-view/render/index.ts
> +    if (!contexts || contexts.length === 0) throw new BeagleParseError('At least one data context should be provided!')
same
```suggestion
    if (!contexts || contexts.length === 0) logger.error(`Beagle can't do the template rendering at the node ${anchor} because it couldn't find any item to render. Please make sure the parameter "contexts" contains at least one element.`)
```

2021-07-01 20:40 UTC, Tiagoperes commented on src/beagle-view/render/index.ts
> +    if (!anchorElement) throw new BeagleParseError(`The anchor element with id "${anchor}" was not found!`)
same
```suggestion
    if (!anchorElement) return beagle.error(`Beagle can't do the template rendering because it couldn't the node identified by the provided anchor: ${anchor}.`)
```

2021-07-01 20:40 UTC, Tiagoperes commented on src/beagle-view/render/index.ts
> +      const contextHierarchy = [...treeContextHierarchy, ...context || []]
the order matters here. The lower the index, the closest it is in the context hierarchy.
```suggestion
      const contextHierarchy = [...context || [], ...treeContextHierarchy]
```

2021-07-01 21:53 UTC, arthurbleilzup commented on src/beagle-view/render/types.ts
> +   * will be used, but only if set, if it is not set the item will be not rendered.
The description will be changed as @Tiagoperes wrote above

2021-07-01 22:01 UTC, arthurbleilzup commented on src/beagle-view/render/types.ts
> +   * to `case`, which is a boolean or a beagle expression that resolves to a boolean. When `case` is
The description will be changed as @Tiagoperes wrote above

2021-07-01 22:02 UTC, arthurbleilzup commented on src/beagle-view/render/types.ts
> +   * an expression, it's resolved using the entire context of the current tree plus the contexts
The description will be changed as @Tiagoperes wrote above

2021-07-01 22:03 UTC, arthurbleilzup commented on src/beagle-view/render/template-manager/types.ts
> +export type ComponentManager = (component: IdentifiableBeagleUIElement, index: number) => Record<string, any>
Because the user wil return only the new attributes, or the changed ones

2021-07-02 11:59 UTC, Tiagoperes commented on src/beagle-view/render/types.ts
> +  /**
```suggestion
/**
```

2021-07-02 12:11 UTC, Tiagoperes commented on src/beagle-view/render/template-manager/types.ts
> +export type ComponentManager = (component: IdentifiableBeagleUIElement, index: number) => Record<string, any>
Every method in Beagle today that can modify part of the tree returns the tree itself. I think it might be unintuitive to have this single method that works differently.

In any case, even if we didn't have other APIs that behaved in a different way. Don't you think it's more intuitive to receive a component and return a component? I think "return only what has changed" is unnecessary logic.

This can be just an opinion though, if you think differently, we can discuss this matter.

2021-07-02 12:29 UTC, Tiagoperes commented on src/beagle-view/render/template-manager/types.ts
> +  case: string | boolean,
Considering this is the core API and not the component interface, does it make any sense for us to expect `boolean | string`. Shouldn't we assume this is always an expression? In terms of API, I can't think of a situation where the user would want to pass a boolean here.

2021-07-02 15:39 UTC, arthurbleilzup commented on __tests__/integration/beagle-keep/assertions/render/templated-home.spec.ts
> +  it('should do three full renders with no errors or warnings', () => {
The test would fail if some warning is shown

2021-07-02 16:06 UTC, arthurbleilzup commented on src/beagle-view/render/template-manager/types.ts
> +export type ComponentManager = (component: IdentifiableBeagleUIElement, index: number) => Record<string, any>
Implemented as suggested

2021-07-02 16:07 UTC, arthurbleilzup commented on src/beagle-view/render/template-manager/types.ts
> +  case: string | boolean,
Implemented as suggested

2021-07-02 16:52 UTC, Tiagoperes approved these changes

2021-07-02 16:52 UTC, Tiagoperes commented on __tests__/unit/beagle-view/render/template.spec.ts
> +      it('should have five child', async () => {
```suggestion
      it('should have five children', async () => {
```

2021-07-02 17:36 UTC, merged