Fix corner radius
ZupIT/beagle-web-core pull request #347
Opened 2021-08-05 21:15 UTC by jamessonpenhazup

**- What I did**
Added support for topLeft, topRight, bottomLeft, bottomRight in corner radius.

**- How I did it**
I changed the corner radius interface.

**- How to verify it**
{
  "_beagleComponent_": "beagle:container",
  "style": {
    "flex": {
      "flexDirection": "COLUMN",
      "alignItems": "CENTER",
      "justifyContent": "CENTER"
    },
    "size": {
      "height": {
        "value": 300,
        "type": "REAL"
      },
      "width": {
        "value": 300,
        "type": "REAL"
      }
    },
    "borderColor": "#FF0000",
    "borderWidth": 20,
    "cornerRadius": {
      "topRight": 0,
      "bottomRight": 50,
      "topLeft": 50,
      "bottomLeft": 0
    }
  }
}

Test with this Json.

**- Description for the changelog**
Closes #https://github.com/ZupIT/beagle/issues/1632

2021-08-06 14:04 UTC, hectorcustodiozup commented on src/beagle-view/render/styling.ts
> +  [key: string]: any,
Is it necessary for this interface to have this pair of values? What else can it expect besides the corner values?

2021-08-09 14:01 UTC, arthurbleilzup commented on src/beagle-view/render/styling.ts
> +  [key: string]: any,
this is to maintain compatibility with the previous `cornerRadius`, which was accepting a `Record<string, any>`

2021-08-09 14:03 UTC, arthurbleilzup requested changes

2021-08-09 14:03 UTC, arthurbleilzup commented on src/beagle-view/render/styling.ts
> +        : {}),
As @hectorcustodiozup commented, now I see that we need to support the old values as well

2021-08-12 20:29 UTC, arthurbleilzup approved these changes

2021-08-17 12:19 UTC, hectorcustodiozup approved these changes

2021-08-17 13:14 UTC, merged