Fixing stack trace of network errors
ZupIT/beagle-web-core pull request #352
Opened 2021-08-18 13:56 UTC by tayronemachadozup

**- What I did**
Improved stack of network errors and beagle cache removal.

**- How I did it**
Adding reponse status and method to BeagleNetworkError. 

**- How to verify it**
Fixing the unit tests and running a case of test in a poc.

**- Description for the changelog**

Closes https://github.com/ZupIT/beagle/issues/1559

2021-08-18 17:33 UTC, jamessonpenhazup commented on __tests__/unit/old-structure/BeagleUIView.spec.ts
> +      new BeagleNetworkError(url, createHttpResponse(),500,'GET'),
```suggestion
      new BeagleNetworkError(url, createHttpResponse(), 500, 'GET'),
```
It would be nice to add the space after the "," to keep a pattern.

2021-08-18 17:33 UTC, jamessonpenhazup commented on __tests__/unit/old-structure/tree-fetching/stratetegies/beagle-cache-only.spec.ts
> +      new BeagleNetworkError(url, {} as Response,500,'GET')
```suggestion
      new BeagleNetworkError(url, {} as Response, 500, 'GET')
```
It would be nice to add the space after the "," to keep a pattern.

2021-08-18 17:33 UTC, jamessonpenhazup commented on __tests__/unit/old-structure/tree-fetching/stratetegies/beagle-with-fallback-to-cache.spec.ts
> +      new BeagleNetworkError(url, {} as Response, 500,'GET'),
```suggestion
      new BeagleNetworkError(url, {} as Response, 500, 'GET'),
```
It would be nice to add the space after the "," to keep a pattern.

2021-08-18 17:33 UTC, jamessonpenhazup commented on __tests__/unit/old-structure/tree-fetching/stratetegies/cache-first.spec.ts
> +      new BeagleNetworkError(url, {} as Response, 500,'GET'),
```suggestion
      new BeagleNetworkError(url, {} as Response, 500, 'GET'),
```
It would be nice to add the space after the "," to keep a pattern.

2021-08-18 17:34 UTC, jamessonpenhazup commented on __tests__/unit/old-structure/tree-fetching/stratetegies/cache-with-fallback-to-network.spec.ts
> +      new BeagleNetworkError(url,undefined,500,'GET'),
```suggestion
      new BeagleNetworkError(url, undefined, 500, 'GET'),
```
It would be nice to add the space after the "," to keep a pattern.

2021-08-18 17:34 UTC, jamessonpenhazup commented on __tests__/unit/old-structure/tree-fetching/stratetegies/network-only.spec.ts
> +      new BeagleNetworkError(url,{} as Response,500 , 'GET'),
```suggestion
      new BeagleNetworkError(url, {} as Response,500 , 'GET'),
```
It would be nice to add the space after the "," to keep a pattern.

2021-08-18 18:21 UTC, arthurbleilzup requested changes

2021-08-18 18:21 UTC, arthurbleilzup commented on src/error/BeagleNetworkError.ts
> +      }
Fix those extra spaces:

```suggestion
        message: this.message,
        response: {
          status: this.response.status,
          statusText: this.response.statusText,
          ok: this.response.ok,
          type: this.response.type,
          redirected: this.response.redirected,
          url: this.response.url,
          headers: this.response.headers,
          text,
          json,
        },
      }
```

2021-08-20 19:21 UTC, arthurbleilzup requested changes

2021-08-20 19:21 UTC, arthurbleilzup commented on src/error/BeagleNetworkError.ts
> +function buildMessage(path: string, responseOrMessage?: Response | string, status?: number, method?: string) {
```suggestion
function buildMessage(path: string, response?: Response | string = '', status?: number, method?: string) {
```

2021-08-20 19:21 UTC, arthurbleilzup commented on src/error/BeagleNetworkError.ts
> +    super(buildMessage(path, responseOrMessage, status, method))
```suggestion
  constructor(path: string, response?: Response | string = '', status?: number, method?: string) {
    super(buildMessage(path, response, status, method))
```

2021-08-20 19:21 UTC, arthurbleilzup commented on src/error/BeagleNetworkError.ts
>    const additionalMessage = typeof responseOrMessage === 'string' ? ` ${responseOrMessage}` : ''
```suggestion
  const additionalMessage = typeof responseOrMessage === 'string' ? `.${responseOrMessage}` : ''
```

2021-08-20 19:21 UTC, arthurbleilzup commented on src/error/BeagleNetworkError.ts
> +  return `network error ${status} while trying to access ${method?.toUpperCase()} ${path}.${additionalMessage}`
```suggestion
  return `network error ${status} while trying to access ${method?.toUpperCase()} ${path}${additionalMessage}`
```

2021-08-20 21:02 UTC, tayronemachadozup commented on src/error/BeagleNetworkError.ts
>    const additionalMessage = typeof responseOrMessage === 'string' ? ` ${responseOrMessage}` : ''
This dot is part of the error message.

2021-08-23 14:29 UTC, arthurbleilzup requested changes

2021-08-23 14:29 UTC, arthurbleilzup commented on src/error/BeagleNetworkError.ts
> +function buildMessage(path: string, responseOrMessage: Response | string ='', status?: number, method?: string) {
```suggestion
function buildMessage(path: string, responseOrMessage: Response | string = '', status?: number, method?: string) {
```

2021-08-23 14:52 UTC, arthurbleilzup approved these changes

2021-08-23 15:00 UTC, jamessonpenhazup approved these changes

2021-08-23 15:00 UTC, merged